package service.webAPI;

public enum Endpoint {
    GET_TASKS,
    GET_TASK_BY_ID,
    POST_TASK,
    DELETE_TASK_BY_ID,
    DELETE_ALL_TASKS,
    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    POST_SUBTASK,
    DELETE_SUBTASK_BY_ID,
    DELETE_ALL_SUBTASKS,
    GET_EPICS,
    GET_EPIC_BY_ID,
    POST_EPIC,
    DELETE_EPIC_BY_ID,
    DELETE_ALL_EPICS,
    GET_PRIORITY_TASKS,
    GET_HISTORY,
    UNKNOWN
}
